<?php

return [
    'paths' => [
        'api/*',
        'sanctum/csrf-cookie',
        'login',
        'logout',
        'register',
        'user',
        'auth/*',
        'bookings',
        'bookings/*',
        'bookings-statistics',
        'quotations',
        'quotations/*',
        'menu-items',
        'menu-items/*',
        'meal-categories',
        'meal-categories/*',
        'meal-categories/manage',
        'packages',
        'packages/*',
        'promotions',
        'promotions/*',
        'ingredients',
        'ingredients/*',
        'recipes',
        'recipes/*',
        'menu-statistics',
        'event-types',
        'calendar-events',
        'booking-calendar/availability',
        'booking-calendar/availability/*',
        'employees',
        'employees/*',
        'schedules',
        'schedules/*',
        'attendance',
        'attendance/*',
        'daily-attendance',
        'daily-attendance/*',
        'payroll',
        'payroll/*',
        'payslips',
        'payslips/*',
        'employee-requests',
        'employee-requests/*',
        'departments',
        'departments/*',
        'positions',
        'positions/*',
        'salary-grades',
        'salary-grades/*',
        'products',
        'products/*',
        'equipment',
        'equipment/*',
        'events',
        'events/*',
        'inventory-history',
        'inventory-history/*',
        'dashboard',
        'dashboard/*',
        'payments',
        'payments/*',
        'invoices',
        'invoices/*',
        'financial-reports',
        'financial-reports/*',
        'shift-types',
        'shift-types/*',
        'orders',
        'orders/*',
        'shopping-list',
        'shopping-list/*',
    ],
    
    'allowed_methods' => ['*'],
    
    'allowed_origins' => [
        'https://catering-management-system-sepia.vercel.app',
        'http://127.0.0.1:5173',
        'http://localhost:5173',
        'http://127.0.0.1:3000',
        'http://localhost:3000',    
        'http://127.0.0.1:8000',
        'http://localhost:8000',
    ],
    
    'allowed_origins_patterns' => [],
    
    'allowed_headers' => ['*'],
    
    'exposed_headers' => [],
    
    'max_age' => 0,
    
    'supports_credentials' => true, // Change this to true for authentication
];